// Post-build patch: wraps OpenNext's worker.js so Wrangler pre-compiles the
// xark WASM module (Workers block runtime WebAssembly compilation). The
// wrapper imports the .wasm file — Wrangler bundles it as a CompiledWasm
// module at deploy time — and exposes it as globalThis.__XARK_WASM.
// At runtime the API route reads globalThis.__XARK_WASM instead of compiling.
//
// Run after `opennextjs-cloudflare build`, before `wrangler deploy`/`preview`.

import { copyFileSync, renameSync, writeFileSync, existsSync } from "node:fs";

const WASM_SRC = "vendor/xark-wasm/xark_wasm_bg.wasm";
const OUT_DIR = ".open-next";
const WORKER = `${OUT_DIR}/worker.js`;
const WORKER_IMPL = `${OUT_DIR}/worker-impl.js`;
const WASM_DST = `${OUT_DIR}/xark_wasm_bg.wasm`;

if (!existsSync(WORKER)) {
  console.error(`patch-wasm: ${WORKER} not found — run opennextjs-cloudflare build first`);
  process.exit(1);
}

// 1. Copy the WASM binary next to the worker.
copyFileSync(WASM_SRC, WASM_DST);

// 2. Rename the original worker.
renameSync(WORKER, WORKER_IMPL);

// 3. Create a wrapper that imports the WASM (Wrangler pre-compiles it),
//    exposes it globally, then re-exports everything from the original worker.
writeFileSync(
  WORKER,
  `// Auto-generated by scripts/patch-wasm.mjs — DO NOT EDIT
// Wraps worker-impl.js to add a Wrangler-compiled WASM import.
import wasmModule from "./xark_wasm_bg.wasm";
globalThis.__XARK_WASM = wasmModule;
export * from "./worker-impl.js";
export { default } from "./worker-impl.js";
`,
);

console.log("✓ patched .open-next/worker.js with WASM import wrapper");
